services:
  bot:
    build: .
    container_name: mirror-bot
    restart: unless-stopped
    stop_grace_period: 40s
    env_file:
      - .env
    ports:
      # Torrent selector
      - "8001:8001"
    volumes:
      - ./data/downloads:/app/downloads
      - ./data/logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
